apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    customer: test-sb
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: gsboone/cg-k8s-web:0.1
        name: web-ctr
        ports:
        - containerPort: 8080
